In [1]:
import json 
import pandas as pd 
import soft_kmeans_alg 
import new_utils 
import json 
import numpy as np 
from scipy.stats import kendalltau
from scipy.stats import mode
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from htcopkmeans.cop_kmeans import cop_kmeans

In [10]:
# j_values = [50, 200, 500]
# r_values = [0.1, 0.25, 0.5, 0.75, 0.9]
# m_values = range(50)  # From 0 to 49 (inclusive)
# temp_json_results_dir = 'temp_json_results/conjugate_priors'
# not_available_fnames_file = 'results/not_available_fnames.txt'

# dic = {}
# dic['param'] = {
#     "num_of_datasets_per_combination": 50,
#     "n_iter": 5000,
#     "n_biomarkers": 10
# }
# not_available_fnames = []
# not_available_count = 0
# for j in j_values:
#     for r in r_values:
#         combstr = f"{int(j*r)}|{j}"
#         if combstr not in dic:
#             dic[combstr] = []
#         for m in m_values:
#             try:
#                 with open(f"{temp_json_results_dir}/temp_results_{j}_{r}_{m}.json") as f:
#                     d = json.load(f)
#                 tau = list(d.values())[0][0]
#                 dic[combstr].append(tau)
#             except:
#                 not_available_count += 1
#                 fname = f"{j} {r} {m}"
#                 not_available_fnames.append(fname)
#                 dic[combstr].append(np.nan)

# print(f"not available: {not_available_count}")
# with open('results/cp_results.json', "w") as file:
#         json.dump(dic, file, indent=4)

In [11]:
# with open(not_available_fnames_file, "w") as f:
#     for item in not_available_fnames:
#         f.write(f"{item}\n")

In [12]:
# with open(not_available_fnames_file, 'r') as f: 
#     loaded_list = [l.strip() for l in f]
# loaded_list

In [13]:
# js = [50, 200, 500]
# rs = [0.1, 0.25, 0.5, 0.75, 0.9]
# num_of_datasets_per_combination = 50
# alist = [
#         f"{int(j*r)}|{j}_{m}"
#         for j in js
#         for r in rs
#         for m in range(num_of_datasets_per_combination)
#     ]

In [14]:
# alist

In [15]:
# with open('temp_json_results/temp_results_50_0.1_0.json') as f:
#     d = json.load(f)
#     print(d)
# print(list(d.values())[0][0])

In [16]:
# # Define the ranges

# j_values = [50, 200, 500]
# r_values = [0.1, 0.25, 0.5, 0.75, 0.9]
# m_values = range(50)  # From 0 to 49 (inclusive)
# # Generate all combinations
# combinations = [f"{j} {r} {m}" for j in j_values for r in r_values for m in m_values]

# all_combinations_file = 'all_combinatinos.txt'
# with open(all_combinations_file, "w") as f:
#     for item in combinations:
#         f.write(f"{item}\n")
# # # Print the result
# # for combo in combinations:
# #     print(combo)

In [17]:
# n_shuffle = 2
# iterations = 100
# burn_in = 10
# thining = 2

In [2]:
data = pd.read_csv("data/5|50_2.csv")
data.head()
n_biomarkers = len(data.biomarker.unique())
biomarker_df = data[data['biomarker'] == "HIP-FCI (1)"].reset_index(drop=True)
biomarker_df.sample(10)

participant    biomarker  measurement  diseased
32           32  HIP-FCI (1)    -7.908987      True
19           19  HIP-FCI (1)   -14.277039      True
27           27  HIP-FCI (1)   -15.195244      True
42           42  HIP-FCI (1)    -7.632697      True
6             6  HIP-FCI (1)    -0.810355      True
11           11  HIP-FCI (1)    -1.043535      True
45           45  HIP-FCI (1)    -8.393027      True
10           10  HIP-FCI (1)    -7.133949      True
33           33  HIP-FCI (1)     1.748016      True
29           29  HIP-FCI (1)    -5.924985      True

In [3]:
from new_utils import compute_theta_phi_for_biomarker 

In [5]:
compute_theta_phi_for_biomarker(biomarker_df)

(np.float64(-9.497793732193427),
 np.float64(3.779865388878283),
 np.float64(0.7903980182975734),
 np.float64(2.887201959751567))

In [6]:
a = [0,0,1,1,0]
cluster_counts = np.bincount(a)
cluster_counts

array([3, 2])

In [4]:
# n_init_value = int(50)
# clustering_setup = KMeans(n_clusters=2, n_init=n_init_value)

# # you need to make sure each measurment is a np.array before putting it into "fit"
# measurements = np.array(biomarker_df['measurement']).reshape(-1, 1)

# # Fit clustering method
# clustering_result = clustering_setup.fit(measurements)
# predictions = clustering_result.labels_

In [5]:
# predictions

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0], dtype=int32)

In [7]:
# counts = np.bincount(predictions)
# counts

array([25, 25])

In [28]:
# all(count > 1 for count in counts)

True

In [24]:
# # dataframe for non-diseased participants
# healthy_df = biomarker_df[biomarker_df['diseased'] == False]
# diseased_df = biomarker_df[biomarker_df['diseased'] == True]
# # healthy_measurements = np.array(healthy_df['measurement']).reshape(-1, 1)
# # which cluster are healthy participants in
# healthy_predictions = predictions[healthy_df.index]
# diseased_predictions = predictions[diseased_df.index]

In [25]:
# healthy_predictions, diseased_predictions

(array([1, 1, 1, 1, 1], dtype=int32),
 array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1], dtype=int32))

## Constrained kmeans

In [8]:
healthy_df = biomarker_df[biomarker_df['diseased'] == False]
diseased_df = biomarker_df[biomarker_df['diseased'] == True]
measurements = np.array(biomarker_df['measurement']).reshape(-1, 1)

In [12]:
healthy_indices = list(healthy_df.index)
diseased_indices = list(diseased_df.index)

In [13]:
healthy_indices, diseased_indices

([1, 12, 28, 35, 39],
 [0,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  29,
  30,
  31,
  32,
  33,
  34,
  36,
  37,
  38,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49])

In [14]:
must_link = [
    (healthy_indices[i], healthy_indices[i+1]) for i in range(
        len(healthy_indices) - 1)]
cannot_link = [(h, d) for h in healthy_indices for d in diseased_indices]

In [15]:
must_link

[(1, 12), (12, 28), (28, 35), (35, 39)]

In [16]:
cannot_link

[(1, 0),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 13),
 (1, 14),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 29),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 33),
 (1, 34),
 (1, 36),
 (1, 37),
 (1, 38),
 (1, 40),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 44),
 (1, 45),
 (1, 46),
 (1, 47),
 (1, 48),
 (1, 49),
 (12, 0),
 (12, 2),
 (12, 3),
 (12, 4),
 (12, 5),
 (12, 6),
 (12, 7),
 (12, 8),
 (12, 9),
 (12, 10),
 (12, 11),
 (12, 13),
 (12, 14),
 (12, 15),
 (12, 16),
 (12, 17),
 (12, 18),
 (12, 19),
 (12, 20),
 (12, 21),
 (12, 22),
 (12, 23),
 (12, 24),
 (12, 25),
 (12, 26),
 (12, 27),
 (12, 29),
 (12, 30),
 (12, 31),
 (12, 32),
 (12, 33),
 (12, 34),
 (12, 36),
 (12, 37),
 (12, 38),
 (12, 40),
 (12, 41),
 (12, 42),
 (12, 43),
 (12, 44),
 (12, 45),
 (12, 46),
 (12, 47),
 (12, 48),
 (12, 49),
 (28, 0),
 (28, 2),
 (28, 3),
 (28, 4),
 (28, 5),
 (28, 6),
 (28, 7),
 (2

In [14]:
# input_matrix = np.random.rand(100, 1)
# input_matrix

In [7]:
clusters, centers = cop_kmeans(dataset=measurements, k=2, ml=must_link)
predictions = np.array(clusters)

In [8]:
predictions

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0])

In [30]:
healthy_predictions = predictions[healthy_df.index]
diseased_predictions = predictions[diseased_df.index]

In [31]:
healthy_predictions

array([1, 1, 1, 1, 1])

In [7]:
# all_current_accepted_order_dicts = soft_kmeans_alg.metropolis_hastings_soft_kmeans(
#     data,
#     iterations,
#     n_shuffle,
# )

In [8]:
# new_utils.save_heatmap(all_current_accepted_order_dicts,
#                        burn_in, thining, folder_name='img',
#                        file_name='test_heatmap', title='heatmap')

In [9]:
# most_likely_order_dic = new_utils.obtain_most_likely_order_dic(
#     all_current_accepted_order_dicts, burn_in, thining)
# most_likely_order = list(most_likely_order_dic.values())
# tau, p_value = kendalltau(most_likely_order, range(1, n_biomarkers + 1))
# dic = {}
# dic['5|50'] = []
# dic['5|50'].append(tau)
# # write the JSON to a file
# with open("results.json", "w") as file:
#     json.dump(dic, file, indent=4)

In [10]:
# new_utils.get_theta_phi_estimates(data)

In [11]:
# biomarker_df.measurement.values

In [12]:
# # reshape to satisfy sklearn requirements
# measurements = np.array(biomarker_df['measurement']).reshape(-1, 1)

# # dataframe for non-diseased participants
# healthy_df = biomarker_df[biomarker_df['diseased'] == False]


In [13]:
# kmeans_setup = KMeans(2, random_state=0, n_init="auto")
# hierarchical_clustering_setup = AgglomerativeClustering(n_clusters=2)

In [14]:
# clustering_result_kmeans = kmeans_setup.fit(measurements)
# clustering_result_kmeans.labels_

In [15]:
# clustering_result_kmeans.predict(measurements)

In [16]:
# theta_mean, theta_std, phi_mean, phi_std = utils.compute_theta_phi_for_biomarker(
#     data, "HIP-FCI (1)", clustering_setup = None)

In [17]:
# theta_mean, theta_std, phi_mean, phi_std

In [18]:
# biomarkers = data.biomarker.unique()
# utils.get_theta_phi_estimates(data, biomarkers)